name: xbde

services:
  xbde-monolith:
    build: .
    container_name: xbde-monolith
    ports:
      - "8090:8090"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped